POST http://{{host}}:{{port}}/api/v1/register HTTP/1.1
Content-Type: application/json

{
    "username": "demo1@demo.com",
    "email": "demo1@demo.com",
    "title": "นาย",
    "firstname": "test_demo_firstname1",
    "lastname": "test_demo_lastname1",
    "password": "demo1"
}

###
POST http://{{host}}:{{port}}/api/v1/register HTTP/1.1
Content-Type: application/json

{
    "username": "demo2@demo.com",
    "email": "demo2@demo.com",
    "title": "นางสาว",
    "firstname": "test_demo_firstname2",
    "lastname": "test_demo_lastname2",
    "password": "demo2"
}

###
POST http://{{host}}:{{port}}/api/v1/register HTTP/1.1
Content-Type: application/json

{
    "username": "demo3@demo.com",
    "email": "demo3@demo.com",
    "title": "นางสาว",
    "firstname": "test_demo_firstname3",
    "lastname": "test_demo_lastname3",
    "password": "demo3"
}

###
POST http://{{host}}:{{port}}/api/v1/register HTTP/1.1
Content-Type: application/json

{
    "username": "demo4@demo.com",
    "email": "demo4@demo.com",
    "title": "นาย",
    "firstname": "test_demo_firstname4",
    "lastname": "test_demo_lastname4",
    "password": "demo4"
}