USE NS ns_template;
USE DB db_template;
CREATE users:iR1f8i7Wg7jipR3uhDhJ CONTENT {
    username: 'demo1@demo.com',
    email: 'demo1@demo.com',
    title: 'นาย',
    firstname: 'first_name_demo',
    lastname: 'last_name_demo',
    password: 'demo1',
    password_salt: u'8eadd57d-8d3c-49e9-90df-e778a9ac3026',
    email_verified: time::now(),
    create_on: time::now(),
    update_on: time::now(),
}
